version: '3'

services:
    vmangos:
        image: vmangos
        build:
            context: .
            dockerfile: docker/Dockerfile

    vmangosd:
        image: vmangos
        container_name: vmangosd
        command: /mangosd
        restart: always
        networks:
            - vmangos_internal
        depends_on:
            - realmd
        volumes:
            - ./data/cnf:/opt/server/etc
            - ./data/maps:/opt/server/maps
            - ./data/logs:/opt/server/logs
            - ./data/honor:/opt/server/honor

    realmd:
        image: vmangos
        container_name: realmd
        command: /realmd
        restart: always
        networks:
            - vmangos_internal
        depends_on:
            - characters_db
            - mangos_db
            - logs_db
            - realmd_db
        volumes:
            - ./data/cnf:/opt/server/etc
            - ./data/maps:/opt/server/maps
            - ./data/logs:/opt/server/logs
            - ./data/honor:/opt/server/honor

    characters_db:
        image: mariadb:10.1.48-bionic
        container_name: characters_db
        environment:
            - MYSQL_ROOT_PASSWORD=characers
            - MYSQL_DATABASE=characters
        restart: on-failure
        networks:
            - vmangos_internal
        ports:
            - "9014:3306"

    mangos_db:
        image: mariadb:10.1.48-bionic
        container_name: mangos_db
        environment:
            - MYSQL_ROOT_PASSWORD=mangos
            - MYSQL_DATABASE=mangos
        restart: on-failure
        networks:
            - vmangos_internal
        ports:
            - "9013:3306"

    logs_db:
        image: mariadb:10.1.48-bionic
        container_name: logs_db
        environment:
            - MYSQL_ROOT_PASSWORD=logs
            - MYSQL_DATABASE=logs
        restart: on-failure
        networks:
            - vmangos_internal
        ports:
            - "9012:3306"

    realmd_db:
        image: mariadb:10.1.48-bionic
        container_name: realmd_db
        environment:
            - MYSQL_ROOT_PASSWORD=realmd
            - MYSQL_DATABASE=realmd
        restart: on-failure
        networks:
            - vmangos_internal
        ports:
            - "9011:3306"

networks:
    vmangos_internal:
